name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest
   steps: 
   - uses: actions/checkout@v2 
   - name: install and run make4ht
     run: |
       sudo apt-get update -y
       sudo apt-get install texlive-extra-utils texlive-luatex tex4ht texlive-latex-extra -y
       make4ht -u -d out polyfaq.tex "mathml,mathjax"
       bibtex polyfaq
       make4ht -u -d out polyfaq.tex "mathml,mathjax"
       cd out
       ln -s polyfaq.html index.html
   - name: Deploy
     uses: JamesIves/github-pages-deploy-action@v4.2.2
     with:
       branch: gh-pages
       folder: out
